### ISSUE TITLE
corrupted release resources published

### ISSUE THREAD

**Issue by gmarcy** [aws/eks-distro-build-tooling#1108]
**What happened**:
it looks like some debugging code may have been present when release artifacts were created. 
discovered installing 1-27-9 but other releases could be affected.

**What you expected to happen**:
the release resources should be valid.

**How to reproduce it (as minimally and precisely as possible)**:
```
# curl https://distro.eks.amazonaws.com/kubernetes-1-27/kubernetes-1-27-eks-9.yaml
value: archive
...
```
which leads to
```
# kubectl apply -f https://distro.eks.amazonaws.com/kubernetes-1-27/kubernetes-1-27-eks-9.yaml
Error from server (BadRequest): error when creating "https://distro.eks.amazonaws.com/kubernetes-1-27/kubernetes-1-27-eks-9.yaml": Release in version "v1alpha1" cannot be handled as a Release: strict decoding error: unknown field "value"
```

**Anything else we need to know?**:
https://github.com/aws/eks-distro-build-tooling/pull/1095#issuecomment-1666588131

**Environment**:
- EKS Distro Release Channel:
- EKS Distro Release: 1-27-9, perhaps others created in the same timeframe

**Comment by rcrozean** [comment]
I believe this should be fixed in the latest versions. Are you still having this issue in https://distro.eks.amazonaws.com/kubernetes-1-27/kubernetes-1-27-eks-11.yaml?

**Comment by markapruett** [comment]
Closing this due to staleness. This issue should have been fixed in the latest release. Feel free to reopen otherwise.
