### ISSUE TITLE
NIST-certified crypto module for deployments that need to be FIPS compliant?

### ISSUE THREAD

**Issue by TerryHowe** [aws/eks-distro-build-tooling#161]
@TerryHowe Are there docs somewhere for how we can generate a build that uses a NIST-certified crypto module for deployments that need to be FIPS compliant?  
Is GoBoring / BoringSSL being setup in some other PR, or is there an alternative solution?

_Originally posted by @markmsmith in https://github.com/aws/eks-distro-build-tooling/issues/53#issuecomment-821575308_

**Comment by seanorama** [comment]
Also looking for this.

According to [this blog post](https://aws.amazon.com/about-aws/whats-new/2021/04/amazon-eks-is-now-fedramp-high-compliant/), AWS EKS has met FedRAMP High compliance.

But that isn't true, as all of it's Go components have not been compiled with a FIPS valid library.

By comparison, GKE is FIPS validated: https://cloud.google.com/security/compliance/fips-140-2-validated/
