### ISSUE TITLE
Add a new project for external-dns to push to helm charts S3

### ISSUE THREAD

**Issue by taneyland** [aws/eks-distro-build-tooling#418]
**What would you like to be added**:
Instead of using a third-party hosted HelmChart repository for external-dns, we should create a new project [here](https://github.com/aws/eks-distro-build-tooling/tree/main/projects) for external-dns and have logic to push charts to our Helm charts S3 bucket on our EKS cluster that we run Prow on. 

**Why is this needed**:
It would be better to use an AWS hosted service to store & retrieve our resources

AC:
* If there isn't already a runbook for how to adding a Helm based project, update the runbook to include the steps.

**Comment by markapruett** [comment]
Thanks @taneyland, 

Do you have any more context for this issue, like the impetus and what the urgency is?
