### ISSUE TITLE
Update EKS-Go badges to reflect new job names

### ISSUE THREAD

**Issue by danbudris** [aws/eks-distro-build-tooling#668]
We've updated the EKS Go prow jobs to use the name format `1-15` rather than `1.15`; we need to update the readme generator for EKS Go and re-run it to re-generate the badges. See https://github.com/aws/eks-distro-build-tooling/blob/main/projects/golang/go/development/scripts/setup_golang_version_readme.sh#L44 and https://github.com/aws/eks-distro-build-tooling/blob/main/projects/golang/go/development/scripts/setup_golang_version_readme.sh#L47

**Comment by danbudris** [comment]
related to https://github.com/aws/eks-distro-prow-jobs/pull/419

**Comment by rcrozean** [comment]
New [EKSGoRelease tool](https://github.com/aws/eks-distro-build-tooling/tree/main/tools/eksDistroBuildToolingOpsTools/pkg/eksGoRelease) accomplishes this.
